### ISSUE TITLE
Freitext-Bewertung - Bug

### ISSUE THREAD

**Issue by tkorner** [ethz-let/moodle-qtype_freehanddrawing#4]
Die Fragen Freihandzeichnen lassen sich nicht über die Freitext-Bewertung korrigieren.
(Die 'Antwortzeichnung/en' werden nur im letzten, auf der Seite, aufgelisteten Studi
angezeigt, und zwar alle Übereinander, cf. Anhang Screenshot.)

Man muss hier bei jedem Studi einzeln die Frage anschauen und korrigieren, über die
Übersicht entweder bei der Frage oder beim 'Review' des Studis.
![screen shot 2014-01-24 at 7 16 02 pm](https://f.cloud.github.com/assets/3245718/2485859/dd93f37c-b11e-11e3-89d1-364ba4ae15c9.png)

**Comment by ghost** [comment]
I have a suggested fix. Please review and let me know if it works for you.
